# Generated by Django 4.2.6 on 2023-10-15 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('parent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото профиля')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='номер телефона')),
                ('whats_up', models.CharField(blank=True, max_length=50, null=True, verbose_name='номер Whats Up')),
                ('pasport_series', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия паспорта')),
                ('profile_status', models.CharField(choices=[('Не подтвержден e-mail', 'Не подтвержден e-mail'), ('Подтверждено', 'Подтверждено')], default='не подтвержден e-mail', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[], max_length=100)),
                ('city', models.CharField(choices=[], max_length=100)),
                ('date_registraion', models.DateTimeField(auto_now=True, verbose_name='дата регистрации команды')),
                ('team_status', models.CharField(choices=[], max_length=50)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
                ('members', models.ManyToManyField(related_name='members', to='main.member')),
            ],
        ),
    ]
